# Generated by Django 3.1.2 on 2020-10-02 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_add_hypertables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False),
        ),
    ]
