# Generated by Django 3.1.2 on 2020-10-02 23:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_auto_20201002_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataPointType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SiteEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.site')),
            ],
        ),
        migrations.CreateModel(
            name='PeripheralComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('controller_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.controllercomponent')),
                ('site_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.siteentity')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('date_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.datapointtype')),
                ('peripheral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.peripheralcomponent')),
            ],
        ),
        migrations.AddField(
            model_name='controllercomponent',
            name='site_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.siteentity'),
        ),
    ]
