# Generated by Django 3.1.2 on 2020-10-03 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_auto_20201002_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoseComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('relative_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_pose_components', to='farms.siteentity')),
                ('site_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pose_component', to='farms.siteentity')),
            ],
        ),
    ]
